### ISSUE TITLE
fail build in latest commit

### ISSUE THREAD

**Issue by sl1pkn07** [IFeelBloated/vsFilterScript#1]
build ok in a2ea68221310c8bf791df68f4b0652985a59f45b

but fails in 2dffdcdf487b1d6725e1ee2f3e103eb23b4790ee

~~~
GaussBlur.hxx: In member function 'auto GaussBlur::DrawFrame(auto:119, auto:120, auto:121)':
GaussBlur.hxx:35:25: error: invalid types 'long int[long int]' for array subscript
   35 |      ProcessedFrame[c][y][x] = GaussBlur(InputFrame[c].View(y, x));
      |                         ^
In file included from EntryPoint.cxx:2:
GaussBlur.hxx: In instantiation of 'auto GaussBlur::DrawFrame(auto:119, auto:120, auto:121) [with auto:119 = int; auto:120 = VaporCore; auto:121 = VSFrameContext*]':
Interface.hxx:26:79:   required from 'auto VaporInterface::Evaluate(auto:99, auto:100, auto:101, auto:102, auto:103, auto:104, auto:105 ...) [with FilterType = GaussBlur; auto:99 = int; auto:100 = int; auto:101 = void**; auto:102 = void**; auto:103 = VSFrameContext*; auto:104 = VSCore*; auto:105 = {const VSAPI*}]'
Interface.hxx:40:3:   required from 'auto VaporInterface::Create(auto:106, auto:107, auto:108, auto:109, auto:110) [with FilterType = GaussBlur; auto:106 = const VSMap*; auto:107 = VSMap*; auto:108 = void*; auto:109 = VSCore*; auto:110 = const VSAPI*]'
Interface.hxx:45:9:   required from 'auto VaporInterface::RegisterFilter(auto:111, auto:112) [with FilterType = GaussBlur; auto:111 = void (*)(const char*, const char*, void (*)(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*), void*, VSPlugin*); auto:112 = VSPlugin*]'
EntryPoint.cxx:9:64:   required from here
GaussBlur.hxx:25:91: error: request for member 'Width' in 'InputFrame.Frame<const float>::operator[]<int>(0)', which is of non-class type 'int'
   25 |   auto ProcessedFrame = Frame<float>{ Core.AllocateFrame(InputFrame.Format, InputFrame[0].Width, InputFrame[0].Height, InputFrame) };
      |                                                                             ~~~~~~~~~~~~~~^~~~~
GaussBlur.hxx:25:112: error: request for member 'Height' in 'InputFrame.Frame<const float>::operator[]<int>(0)', which is of non-class type 'int'
   25 |   auto ProcessedFrame = Frame<float>{ Core.AllocateFrame(InputFrame.Format, InputFrame[0].Width, InputFrame[0].Height, InputFrame) };
      |                                                                                                  ~~~~~~~~~~~~~~^~~~~~
GaussBlur.hxx:25:8: error: no matching function for call to 'Frame<float>::Frame(<brace-enclosed initializer list>)'
   25 |   auto ProcessedFrame = Frame<float>{ Core.AllocateFrame(InputFrame.Format, InputFrame[0].Width, InputFrame[0].Height, InputFrame) };
      |        ^~~~~~~~~~~~~~
In file included from Clip.hxx:2,
                 from Map.hxx:2,
                 from Interface.hxx:2,
                 from EntryPoint.cxx:1:
Frame.hxx:24:2: note: candidate: 'Frame<PixelType>::Frame(Frame<PixelType>&&) [with PixelType = float]'
   24 |  Frame(Frame&& OtherFrame) {
      |  ^~~~~
Frame.hxx:24:2: note:   conversion of argument 1 would be ill-formed:
Frame.hxx:21:2: note: candidate: 'Frame<PixelType>::Frame(const Frame<PixelType>&) [with PixelType = float]'
   21 |  Frame(const Frame& OtherFrame) {
      |  ^~~~~
Frame.hxx:21:2: note:   conversion of argument 1 would be ill-formed:
Frame.hxx:15:2: note: candidate: 'template<class auto:43> Frame<PixelType>::Frame(auto:43)'
   15 |  Frame(auto RawFrame) {
      |  ^~~~~
Frame.hxx:15:2: note:   template argument deduction/substitution failed:
Frame.hxx:14:2: note: candidate: 'constexpr Frame<PixelType>::Frame() [with PixelType = float]'
   14 |  Frame() = default;
      |  ^~~~~
Frame.hxx:14:2: note:   candidate expects 0 arguments, 1 provided
In file included from EntryPoint.cxx:2:
GaussBlur.hxx:33:39: error: request for member 'Height' in 'InputFrame.Frame<const float>::operator[]<long int>(c)', which is of non-class type 'long int'
   33 |    for (auto y : Range{ InputFrame[c].Height })
      |                         ~~~~~~~~~~~~~~^~~~~~
GaussBlur.hxx:33:4: error: no matching function for call to 'Range::Range(<brace-enclosed initializer list>)'
   33 |    for (auto y : Range{ InputFrame[c].Height })
      |    ^~~
In file included from Plane.hxx:2,
                 from Frame.hxx:3,
                 from Clip.hxx:2,
                 from Map.hxx:2,
                 from Interface.hxx:2,
                 from EntryPoint.cxx:1:
Range.hxx:38:2: note: candidate: 'template<class auto:12, class auto:13, class auto:14> Range::Range(auto:12, auto:13, auto:14)'
   38 |  Range(auto Startpoint, auto Endpoint, auto Step) {
      |  ^~~~~
Range.hxx:38:2: note:   template argument deduction/substitution failed:
Range.hxx:32:2: note: candidate: 'template<class auto:10, class auto:11> Range::Range(auto:10, auto:11)'
   32 |  Range(auto Startpoint, auto Endpoint) {
      |  ^~~~~
Range.hxx:32:2: note:   template argument deduction/substitution failed:
Range.hxx:27:2: note: candidate: 'template<class auto:9> Range::Range(auto:9)'
   27 |  Range(auto Endpoint) {
      |  ^~~~~
Range.hxx:27:2: note:   template argument deduction/substitution failed:
Range.hxx:26:2: note: candidate: 'constexpr Range::Range()'
   26 |  Range() = default;
      |  ^~~~~
Range.hxx:26:2: note:   candidate expects 0 arguments, 1 provided
Range.hxx:4:7: note: candidate: 'constexpr Range::Range(const Range&)'
    4 | class Range final {
      |       ^~~~~
Range.hxx:4:7: note:   conversion of argument 1 would be ill-formed:
Range.hxx:4:7: note: candidate: 'constexpr Range::Range(Range&&)'
Range.hxx:4:7: note:   conversion of argument 1 would be ill-formed:
In file included from EntryPoint.cxx:2:
GaussBlur.hxx:34:40: error: request for member 'Width' in 'InputFrame.Frame<const float>::operator[]<long int>(c)', which is of non-class type 'long int'
   34 |     for (auto x : Range{ InputFrame[c].Width })
      |                          ~~~~~~~~~~~~~~^~~~~
GaussBlur.hxx:34:5: error: no matching function for call to 'Range::Range(<brace-enclosed initializer list>)'
   34 |     for (auto x : Range{ InputFrame[c].Width })
      |     ^~~
In file included from Plane.hxx:2,
                 from Frame.hxx:3,
                 from Clip.hxx:2,
                 from Map.hxx:2,
                 from Interface.hxx:2,
                 from EntryPoint.cxx:1:
Range.hxx:38:2: note: candidate: 'template<class auto:12, class auto:13, class auto:14> Range::Range(auto:12, auto:13, auto:14)'
   38 |  Range(auto Startpoint, auto Endpoint, auto Step) {
      |  ^~~~~
Range.hxx:38:2: note:   template argument deduction/substitution failed:
Range.hxx:32:2: note: candidate: 'template<class auto:10, class auto:11> Range::Range(auto:10, auto:11)'
   32 |  Range(auto Startpoint, auto Endpoint) {
      |  ^~~~~
Range.hxx:32:2: note:   template argument deduction/substitution failed:
Range.hxx:27:2: note: candidate: 'template<class auto:9> Range::Range(auto:9)'
   27 |  Range(auto Endpoint) {
      |  ^~~~~
Range.hxx:27:2: note:   template argument deduction/substitution failed:
Range.hxx:26:2: note: candidate: 'constexpr Range::Range()'
   26 |  Range() = default;
      |  ^~~~~
Range.hxx:26:2: note:   candidate expects 0 arguments, 1 provided
Range.hxx:4:7: note: candidate: 'constexpr Range::Range(const Range&)'
    4 | class Range final {
      |       ^~~~~
Range.hxx:4:7: note:   conversion of argument 1 would be ill-formed:
Range.hxx:4:7: note: candidate: 'constexpr Range::Range(Range&&)'
Range.hxx:4:7: note:   conversion of argument 1 would be ill-formed:
In file included from EntryPoint.cxx:2:
GaussBlur.hxx:35:56: error: request for member 'View' in 'InputFrame.Frame<const float>::operator[]<long int>(c)', which is of non-class type 'long int'
   35 |      ProcessedFrame[c][y][x] = GaussBlur(InputFrame[c].View(y, x));
      |                                          ~~~~~~~~~~~~~~^~~~
In file included from Clip.hxx:2,
                 from Map.hxx:2,
                 from Interface.hxx:2,
                 from EntryPoint.cxx:1:
Frame.hxx: In instantiation of 'auto& Frame<PixelType>::operator[](auto:46) [with auto:46 = int; PixelType = const float]':
GaussBlur.hxx:25:87:   required from 'auto GaussBlur::DrawFrame(auto:119, auto:120, auto:121) [with auto:119 = int; auto:120 = VaporCore; auto:121 = VSFrameContext*]'
Interface.hxx:26:79:   required from 'auto VaporInterface::Evaluate(auto:99, auto:100, auto:101, auto:102, auto:103, auto:104, auto:105 ...) [with FilterType = GaussBlur; auto:99 = int; auto:100 = int; auto:101 = void**; auto:102 = void**; auto:103 = VSFrameContext*; auto:104 = VSCore*; auto:105 = {const VSAPI*}]'
Interface.hxx:40:3:   required from 'auto VaporInterface::Create(auto:106, auto:107, auto:108, auto:109, auto:110) [with FilterType = GaussBlur; auto:106 = const VSMap*; auto:107 = VSMap*; auto:108 = void*; auto:109 = VSCore*; auto:110 = const VSAPI*]'
Interface.hxx:45:9:   required from 'auto VaporInterface::RegisterFilter(auto:111, auto:112) [with FilterType = GaussBlur; auto:111 = void (*)(const char*, const char*, void (*)(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*), void*, VSPlugin*); auto:112 = VSPlugin*]'
EntryPoint.cxx:9:64:   required from here
Frame.hxx:60:22: error: invalid initialization of reference of type 'int&' from expression of type 'std::array<Plane<const float, PaddingPolicies::Spatial::<lambda(auto:33, auto:34, auto:35, auto:36, auto:37)> >, 3>::value_type' {aka 'Plane<const float, PaddingPolicies::Spatial::<lambda(auto:33, auto:34, auto:35, auto:36, auto:37)> >'}
   60 |   return Planes[Index];
      |                      ^
make: *** [Makefile:2: all] Error 1
~~~

gcc 9.3.0

rules:
~~~
g++ -c -std=c++2a -fPIC -march=native -O3 -pipe -fno-plt -D_FORTIFY_SOURCE=2 -I. -I/usr/include/vapoursynth  -o EntryPoint.o EntryPoint.cxx
g++ -shared -fPIC -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -lstdc++ -o lib${_plug}.so EntryPoint.o"
~~~

**Comment by IFeelBloated** [comment]
you need the latest GCC from the trunk.
GCC 9 has a known bug with abbreviated templates and does not support CTAD for aggregates (C++20 feature).

**Comment by IFeelBloated** [comment]
to make GCC 9 happy,
change [line59](https://github.com/IFeelBloated/vsFilterScript/blob/master/Frame.hxx#L59) to
`template<typename T>`
`auto& operator[](T Index)`
and do the same for [line16 here](https://github.com/IFeelBloated/vsFilterScript/blob/master/Clip.hxx#L16) and [here](https://github.com/IFeelBloated/vsFilterScript/blob/master/Clip.hxx#L27)

then change [here](https://github.com/IFeelBloated/vsFilterScript/blob/master/Clip.hxx#L90) to
`return Sequence<std::vector<Frame<PixelType>>>{ .Container = std::move(Container), .Radius = Radius };`

let me know if this works

**Comment by sl1pkn07** [comment]
<details>

~~~patch
diff --git a/Clip.hxx b/Clip.hxx
index 5a88f83..978d656 100644
--- a/Clip.hxx
+++ b/Clip.hxx
@@ -13,7 +13,7 @@ struct Clip final {
 		struct Offset final {
 			self(State, static_cast<Sequence*>(nullptr));
 			self(tOffset, 0_ptrdiff);
-			auto& operator[](auto t) {
+			auto& operator[](T Index) {
 				auto& ReferenceSequence = *State;
 				return ReferenceSequence[t + tOffset];
 			}
@@ -24,7 +24,7 @@ struct Clip final {
 				return Offset{ .State = State, .tOffset = tOffset + t };
 			}
 		};
-		auto& operator[](auto t) {
+		auto& operator[](T Index) {
 			return Container[t + Radius];
 		}
 		auto View(auto t) {
@@ -87,7 +87,7 @@ struct Clip final {
 		auto Container = std::vector<Frame<PixelType>>{};
 		for (auto Offset : Range{ Index - Radius, Index + Radius + 1 })
 			Container.push_back(GetFrame<PixelType>(Offset, PaddingPolicy, FrameContext, Forward(AuxiliaryArguments)...));
-		return Sequence{ .Container = std::move(Container), .Radius = Radius };
+		return Sequence<std::vector<Frame<PixelType>>>{ .Container = std::move(Container), .Radius = Radius };
 	}
 	template<typename PixelType>
 	auto GetFrames(auto Index, auto Radius, auto FrameContext) {
@@ -102,4 +102,4 @@ struct Clip final {
 	auto WithConstantFormat() {
 		return Info->format != nullptr;
 	}
-};
\ No newline at end of file
+};
diff --git a/Frame.hxx b/Frame.hxx
index ef1f9f9..9e2d6f8 100644
--- a/Frame.hxx
+++ b/Frame.hxx
@@ -56,8 +56,8 @@ struct Frame final {
 		};
 		return Plane<PixelType, PolicyType>{ GetPlanePointer(), Width, Height, Forward(PaddingPolicy) };
 	}
-	auto& operator[](auto Index) {
-		return Planes[Index];
+	template<typename T>
+		auto& operator[](T Index)
 	}
 	auto Leak() {
 		auto LeakedFrame = RawFrame;
@@ -70,4 +70,4 @@ struct Frame final {
 		else
 			return RawFrame;
 	}
-};
\ No newline at end of file
+};
~~~

</details>


~~~
In file included from EntryPoint.cxx:2:
GaussBlur.hxx:35:52: error: no match for 'operator[]' (operand types are 'Frame<const float>' and 'long int')
   35 |      ProcessedFrame[c][y][x] = GaussBlur(InputFrame[c].View(y, x));
      |                                          ~~~~~~~~~~^
In file included from EntryPoint.cxx:1:
Interface.hxx: In instantiation of 'auto VaporInterface::Evaluate(auto:96, auto:97, auto:98, auto:99, auto:100, auto:101, auto:102 ...) [with FilterType = GaussBlur; auto:96 = int; auto:97 = int; auto:98 = void**; auto:99 = void**; auto:100 = VSFrameContext*; auto:101 = VSCore*; auto:102 = {const VSAPI*}]':
Interface.hxx:40:3:   required from 'auto VaporInterface::Create(auto:103, auto:104, auto:105, auto:106, auto:107) [with FilterType = GaussBlur; auto:103 = const VSMap*; auto:104 = VSMap*; auto:105 = void*; auto:106 = VSCore*; auto:107 = const VSAPI*]'
Interface.hxx:45:9:   required from 'auto VaporInterface::RegisterFilter(auto:108, auto:109) [with FilterType = GaussBlur; auto:108 = void (*)(const char*, const char*, void (*)(const VSMap*, VSMap*, void*, VSCore*, const VSAPI*), void*, VSPlugin*); auto:109 = VSPlugin*]'
EntryPoint.cxx:9:64:   required from here
Interface.hxx:26:79: error: 'struct Frame<float>' has no member named 'Leak'
   26 |    return Data->DrawFrame(Index, VaporCore{ .Instance = Core }, FrameContext).Leak();
make: *** [Makefile:2: all] Error 1
~~~

**Comment by IFeelBloated** [comment]
I have confirmed that the [GCC9 branch](https://github.com/IFeelBloated/vsFilterScript/tree/GCC9) works with GCC9.2
g++ -shared -std=c++2a -fconcepts -lstdc++ -static -O3 -o Filter.dll EntryPoint.cxx

**Comment by sl1pkn07** [comment]
not with gcc 9.3 :(, or i do bad the patch

**Comment by IFeelBloated** [comment]
> not with gcc 9.3 :(, or i do bad the patch

the GCC9 branch is already patched. you don't need to patch it again.

**Comment by sl1pkn07** [comment]
oh, i missread the comment. yes. now works

tnx!

edit: yep. i do bad the patch
